### ISSUE TITLE
Failed during checkstyle execution: There are 55 errors reported by Checkstyle 6.18 with checkstyle.xml ruleset

### ISSUE THREAD

**Issue by javadev** [blynkkk/clickhouse4j#35]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project clickh
ouse4j: Failed during checkstyle execution: There are 55 errors reported by Checkstyle 6.18 with checkstyle.xml ruleset.

**Comment by doom369** [comment]
@javadev Thanks for the report. Could you please clarify how do you run checkstyle check? Checkstyle was fixed recently after merge from the upstream.

**Comment by javadev** [comment]
I started command:

```
mvn clean test-compile
```

**Comment by doom369** [comment]
@javadev fixed, thanks again. Please close the issue of all is ok.

**Comment by javadev** [comment]
There are checkstyle errors. I use maven 3.6.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project clickh
ouse4j: Failed during checkstyle execution: There are 96 errors reported by Checkstyle 6.18 with checkstyle.xml ruleset.
 -> [Help 1]
```

**Comment by doom369** [comment]
@javadev please post error log with exact errors.

**Comment by javadev** [comment]
[result.txt](https://github.com/blynkkk/clickhouse4j/files/3578340/result.txt)

**Comment by javadev** [comment]
@doom369 It may be widows/git related issue. All java files has 0A character at the end.

**Comment by doom369** [comment]
@javadev pushed the fix. Please check again.

**Comment by javadev** [comment]
Compilation works for me.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 min
[INFO] Finished at: 2019-09-05T12:14:10+03:00
[INFO] ------------------------------------------------------------------------
```
