### ISSUE TITLE
Empty Authorization header is submitted if no auth is defined 

### ISSUE THREAD

**Issue by yonatang** [blynkkk/clickhouse4j#83]
If the `Authorization` parameter is not passed, clickhouse4j will send an HTTP request with an empty `Authorization` header:
```
POST /?user=default&database=default&compress=1 HTTP/1.1
Authorization
Content-Type: text/plain; charset=UTF-8
User-Agent: Java/11.0.1
Host: localhost:8123
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 55

select timezone() FORMAT TabSeparatedWithNamesAndTypes
```

Usually, it is meaningless, since Clickhouse just ignore that header, but in some cases (i.e. proxies, such as https://github.com/Vertamedia/chproxy/issues/81), it might cause the request to fail. Because this header isn't actually required, it should better not be sent at all.

**Comment by yonatang** [comment]
I just saw it was resolved 10 days ago in https://github.com/yonatang/clickhouse4j/commit/195816ae3ea8737ae9360fe7be884af0bc2f9b78

**Comment by doom369** [comment]
@yonatang correct. Please update to the 1.4.4 version. Thanks for the report anyway.
