### ISSUE TITLE
Merge changes back to official JDBC driver

### ISSUE THREAD

**Issue by zhicwu** [blynkkk/clickhouse4j#90]
Hello @doom369, very impressive work! I'm taking over official JDBC driver development. The first thing I want to do is removing unnecessary dependencies, hence I'm wondering if I can port some of your work there. Please let me know if there's any concern.

**Comment by doom369** [comment]
@zhicwu glad to hear that. Sure, you can port any changes you want. In fact, I initially tried to contribute those changes to the original driver, but they never were accepted. So you're welcome.

**Comment by zhicwu** [comment]
Thanks @doom369. I guess the maintainer was busy at that time. Anyway, I'll start to create a PR for this in late Dec. Will definitely mention you there in case you have time to review. Thanks in advance!
